import { IonButtons, IonContent, IonHeader, IonIcon, IonModal, IonTitle, IonToolbar } from '@ionic/react';
import { caretBack, caretForwardOutline } from 'ionicons/icons';
import { useState } from 'react';
import { DifficultyDto } from '../../enum/difficulty.js';
import ButtonComponent from '../button/button.js';
import HeadingComponent from '../heading/heading.js';
import bustsvg from './../../assets/svg/bust.svg'
import blackflagsvg from './../../assets/svg/blackflag.svg'
import './challengeitems.css';

interface ContainerProps {
  days: string;
  hours: string;
  categorie: string;
  challenge: string;
  difficulty: DifficultyDto;
  image: string;
}

const ChallengeItemsComponent: React.FC<ContainerProps> = ({ ...props }) => {
  const [showModal, setShowModal] = useState(false);

  const openModal = () => {
    setShowModal(true);
  };

  return (
    <div className="challenge-items-container">
      {/* Arrow redirection */}
      <div className="arrow-icon-container" onClick={openModal}>
        <IonIcon icon={caretForwardOutline} className='challenge-items-caretForwardOutline' />
      </div>

      {/* Logo */}
      <div className="challenge-items-logo-area flex" style={{ backgroundImage: `url(${props.image})` }}></div>

      {/* Title / Description */}
      <div className="challenge-items-text column">
        {/* Date */}
        <div>
          <span style={{ fontWeight: "600" }}>{props.days}</span> - {props.hours}
        </div>

        {/* Description */}
        <div style={{ overflow: 'hidden', textOverflow: 'ellipsis', display: '-webkit-box', WebkitBoxOrient: 'vertical', WebkitLineClamp: 2 }}>
          {props.challenge}
        </div>
      </div>

      {/* Modal */}
      <IonModal isOpen={showModal} onDidDismiss={() => setShowModal(false)}>
        <IonHeader>
          <IonToolbar>
            <IonButtons slot="start">
              <IonIcon onClick={() => setShowModal(false)} icon={caretBack} size='medium' />
            </IonButtons>

            <IonTitle>Challenge</IonTitle>
          </IonToolbar>
        </IonHeader>

        <IonContent className='ion-padding challenge-modal-container'>
          <div className="challenge-modal-container">
            {/* Content */}
            <div className="challenge-modal-content">
              <div style={{ fontSize: "1.1rem" }}><span style={{ fontWeight: "600", fontSize: "1.15rem" }}>Challenge: </span>{props.challenge}</div>

              <div className="challenge-modal-infos-container">
                <img className="challenge-modal-image" src={props.image} alt="" />

                <div className="challenge-modal-infos">
                  <div><span style={{ fontWeight: "600" }}>Generated by: </span> <span style={{ textDecoration: "underline" }}>@thomasperge</span></div>
                  <div><span style={{ fontWeight: "600" }}>Status: </span> <span style={{color: "var(--ion-color-500)", fontWeight: "500"}}>Finished</span> ({props.days} {props.hours})</div>
                  <div><span style={{ fontWeight: "600" }}>Duration: </span> <span style={{fontWeight: "500"}}>2d 18h</span></div>
                </div>
              </div>

              {/* People */}
              <div style={{ display: "flex", flexDirection: "column", gap: ".5rem" }}>
                <HeadingComponent
                  text="People's"
                  fontSize="1.15rem"
                  fontWeight="600"
                />

                <div className="challenge-modal-people-container">
                  <div className="flex" style={{ gap: ".25rem", fontSize: "1.05rem", justifyContent: "start" }}>
                    <img src={bustsvg} style={{ width: "18px", height: "18px" }} className='flex' alt="" />
                    <span style={{ fontWeight: "600", fontSize: "1.11rem" }}>758</span>joined this challenge
                  </div>

                  <div className="flex" style={{ gap: ".25rem", fontSize: "1.05rem", justifyContent: "start" }}>
                    <img src={blackflagsvg} style={{ width: "18px", height: "18px" }} className='flex' alt="" />
                    <span style={{ fontWeight: "600", fontSize: "1.11rem" }}>12</span>finished
                  </div>

                  <div className="challenge-modal-people-joined"><span style={{ fontWeight: "600", fontSize: "1.11rem" }}>Average time:</span> 3d 12h</div>
                </div>
              </div>

            </div>

            {/* Button */}
            <div className="challenge-modal-button">
              <ButtonComponent
                text="Redo"
                width='100%'
                background='var(--ion-gradient-400)'
                padding='.4rem 2rem'
                color='white'
                fontSize='1rem'
                fontWeight='500'
                borderRadius='8px'
              ></ButtonComponent>

              <ButtonComponent
                text="Delete"
                width='100%'
                padding='.4rem 2rem'
                fontSize='1rem'
                fontWeight='500'
                borderRadius='8px'
                className='challenge-modal-button-not-selected'
              ></ButtonComponent>
            </div>
          </div>
        </IonContent>
      </IonModal>

    </div>
  );
};

export default ChallengeItemsComponent;
